.gitignore
package.json
src/App.js

all finger dots rendering correctly

Map circles

---

src/App.js

all symbols toggling correctly now

Open muted string symbols

---

package.json
src/App.js
src/components/SaveButton.js

- Add axios
- Add SaveButton component.

Add save ability

---

src/components/AllChordSheets.js
src/components/chord-sheet/ChordSheet.js
src/index.css
src/routes.js

- Change `setState` calls to use function instead of object.
-  Using a function instead of an object as an argument to setState is explained here: (https://medium.com/@shopsifter/using-a-function-in-setstate-instead-of-an-object-1f5cfd6e55d1)
- Add navigation at the top

Refactor `setState` and apply basic style to nav links

---

package.json
src/client/src/App.js
src/client/src/Auth.js
src/client/src/components/AllChordSheets.js
src/client/src/components/PrivateRoute.js
src/client/src/components/chord-sheet/ToolBar.js
src/client/src/components/forms/Login.js
src/server/app.js
src/server/routes.js

Remove cypress.io
Reimplement prev auth logic
Convert login form to proper react style

Remove cypress, reimplement prev auth logic

---

Makefile
README.md
src/variables.env

tested. Saves a few key strokes with make commands!

modify makefile and readme

---

.github/workflows/publish_docker_hub.yml
package-lock.json

When this is merged, the action should run
It doesn't do much yet...

initial test action

---

.github/workflows/test_actions.yml

We can use this branch to test actions with dummy code changes. This action shouldn't run unless a change is made to `src/server` contents on only this branch

add testing branch for actions

---

.github/workflows/publish_docker.yml

add steps to login, build, and publish docker image

---

.github/workflows/publish_docker.yml

Add SSH into Digital Ocean to Github Action

---

.github/workflows/publish_docker.yml

this should get past the hang up in the SSH step

run in detached mode

---

src/server/app.js

Set CLIENT_URL in .env file
Replace hard coded URL with process.env.CLIENT_URL

Allow CORS requests from client

---

src/server/app.js

- front end and back end are now on the same domain
- Same site Strict applies
- should no longer need Secure

Set same-site on cookie to strict and remove Secure

---

src/client/src/components/forms/Login.js
src/server/app.js

Log entire response from server after login request

Expose set-cookie in Cors Options

---

src/server/app.js

remove exposedHeaders from cors

---

src/client/src/components/forms/Login.js

withCredentials as default seemed to add a cookie that I do not know where it is coming from

remove default axis withcredentials.

---

src/client/src/components/forms/Login.js

 move credentials up

---

src/server/app.js

I think this might have done something actually...

expose set-cookie header again

---

package-lock.json
package.json
src/server/tests/routes.test.js
src/server/tests/sample.test.js

I've got a simple Jest running, but now need to figure out how to run all this inside the docker container.

Setup Jest

---

src/client/src/components/forms/Login.js

Update from Class component to Function Component
Replace setState with useState hook

Update Login Component

---

src/client/src/components/forms/Login.js
src/client/src/components/forms/Register.js

Update Register to a function component that uses the useReducer hook

Update Register Component
